### ISSUE TITLE
Not working anymore on Raspberry Pi 4

### ISSUE THREAD

**Issue by bjoern-vh** [flosoft/docker-joplin-server#11]
Hello,
I have been using your image since August 2021 and have had no problems. Suddenly nothing runs since yesterday. The container is always restarting and in the logs is always only:

`
joplin-app | standard_init_linux.go:228: exec user process caused: exec format error
`
This is my docker-compose file:

```
version: '3'

services:
    joplin-app:
        image: florider89/joplin-server:latest
        container_name: joplin-app
        environment:
            - APP_BASE_URL=https://###
            - APP_PORT=22300
            - POSTGRES_PASSWORD=${POSTGRES_PWD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=joplin-db
            - DB_CLIENT=pg
        restart: unless-stopped
        networks:
            - default
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.joplin.rule=Host(`###`)"
            - "traefik.http.routers.joplin.entrypoints=websecure"
            - "traefik.http.routers.joplin.tls=true"
            - "traefik.http.routers.joplin.tls.certresolver=default"
            - "traefik.http.services.joplin-server.loadbalancer.server.port=22300"
            - "traefik.docker.network=traefik_proxy"

    joplin-db:
        restart: unless-stopped
        image: postgres:13
        container_name: joplin-db
        hostname: joplin-db
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PWD}
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplin

networks:
  traefik_proxy:
    external: true
```

According to docker inspect I have image version 2.6.3 in use. Although my tag is set to latest, no updates come when I call pull.

`
OS: RaspianOS 64-Bit (Debian GNU/Linux 10 (buster)
Docker version: 20.10.12
Docker-compose version: 1.29.2
`
If you need more information, please ask for it. I will try to add it then.

Thanks in advance!

Kind regards,
Bjoern
