### ISSUE TITLE
Getting Nodejs errors

### ISSUE THREAD

**Issue by gtlsgamr** [flosoft/docker-joplin-server#8]
Hello. I am running the latest image on Rpi64 bit image. The Database starts fine, but the app seems to get this error. 

```joplin_app_1 exited with code 132
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
app_1  | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by malammar** [comment]
Seeing the same issue on arm64 raspberry pi.

**Comment by malammar** [comment]
Figured this out. You need to add these options to the docker-compose:

```
---
version: "3"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    security_opt: # this option
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=waNhNrxX3zfnTg #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=webtv1987 #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.malammar.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```
